runtime: python39

instance_class: F2

env_variables:
  FLASK_ENV: "production"
  # Note: Do not put actual secrets here.
  # Use Secret Manager in production

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
